created readme file
QQBratka/taxi-service pull request #1
Opened 2021-12-15 12:35 UTC by QQBratka

2021-12-15 14:32 UTC, PineappleApplePinecone requested changes

2021-12-15 14:32 UTC, PineappleApplePinecone commented on README.md
> +
I think this spaces is not necessary

2021-12-15 14:32 UTC, PineappleApplePinecone commented on README.md
> +
here

2021-12-15 14:32 UTC, PineappleApplePinecone commented on README.md
> +
here and so on

2021-12-15 14:36 UTC, PineappleApplePinecone approved these changes

2021-12-15 15:01 UTC, Nick97-git requested changes
- DeleteCarController, DeleteDriverController, DeleteManufacturerController -> remove /all from /cars/all, /drivers/all, /manufacturers/all url patterns
- GetMyCurrentCarsController -> Long id -> Long driverId

2021-12-15 15:01 UTC, Nick97-git commented on README.md
> +## Project description:
```suggestion
## Available functions:
```

2021-12-15 15:01 UTC, Nick97-git commented on README.md
> +* Relations many to one, many to many
remove this line

2021-12-15 15:01 UTC, Nick97-git commented on README.md
> +* Maven checkstyle plugin
remove this line

2021-12-15 15:01 UTC, Nick97-git commented on README.md
> +* For using logger change full path in log4j2.xml file
make a numbered list of it

2021-12-15 15:01 UTC, Nick97-git commented on README.md
> +* Create a schema like in resources/init_db.sql in MySQL Workbench
```suggestion
* Create a schema in MySQL Workbench using resources/init_db.sql
```

2021-12-15 15:01 UTC, Nick97-git commented on README.md
> +* MySQL and MySQL Workbench
what to do with them install or something else?

2021-12-16 06:50 UTC, Nick97-git commented
what about comments not related to Readme?

2021-12-16 08:33 UTC, Nick97-git approved these changes

2021-12-16 08:34 UTC, merged